/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.net.httpserver.Filter;
import javax.swing.JRadioButton;

/**
 *
 * @author Oldřich
 */
public class pnlVstup extends javax.swing.JPanel {

    /**
     * Creates new form pnlVstup
     */
    private char hodnota;
    private JRadioButton[] moznosti = new JRadioButton[10];

    public pnlVstup() {
        initComponents();
        initMoznosti();
        moznosti[0].setSelected(true);
    }

    public pnlVstup(char hodnota) {

        initComponents();
        initMoznosti();
        moznosti[Character.getNumericValue(hodnota)].setSelected(true);
    }

    private void initMoznosti() {
        moznosti[1] = rbt1;
        moznosti[2] = rbt2;
        moznosti[3] = rbt3;
        moznosti[4] = rbt4;
        moznosti[5] = rbt5;
        moznosti[6] = rbt6;
        moznosti[7] = rbt7;
        moznosti[8] = rbt8;
        moznosti[9] = rbt9;
        moznosti[0] = tbtNic;
    }

    public char getHodnota() {
        for (int i = 0; i < moznosti.length; i++) {
            if (moznosti[i].isSelected()) {
                hodnota = Character.forDigit(i, 10);
                break;
            }
        }
        return hodnota;
    }

    public void setHodnota(char hodnota) {
        this.hodnota = hodnota;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgVolba = new javax.swing.ButtonGroup();
        rbt1 = new javax.swing.JRadioButton();
        rbt2 = new javax.swing.JRadioButton();
        rbt3 = new javax.swing.JRadioButton();
        rbt4 = new javax.swing.JRadioButton();
        rbt5 = new javax.swing.JRadioButton();
        rbt6 = new javax.swing.JRadioButton();
        rbt7 = new javax.swing.JRadioButton();
        rbt8 = new javax.swing.JRadioButton();
        rbt9 = new javax.swing.JRadioButton();
        tbtNic = new javax.swing.JRadioButton();
        lblPopis = new javax.swing.JLabel();

        btgVolba.add(rbt1);
        rbt1.setText("1");

        btgVolba.add(rbt2);
        rbt2.setText("2");

        btgVolba.add(rbt3);
        rbt3.setText("3");

        btgVolba.add(rbt4);
        rbt4.setText("4");

        btgVolba.add(rbt5);
        rbt5.setText("5");

        btgVolba.add(rbt6);
        rbt6.setText("6");

        btgVolba.add(rbt7);
        rbt7.setText("7");

        btgVolba.add(rbt8);
        rbt8.setText("8");

        btgVolba.add(rbt9);
        rbt9.setText("9");

        btgVolba.add(tbtNic);
        tbtNic.setText("Nic");

        lblPopis.setText("Vyberte cislo ke vlozeni:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbt4)
                        .addGap(18, 18, 18)
                        .addComponent(rbt5)
                        .addGap(18, 18, 18)
                        .addComponent(rbt6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbt1)
                        .addGap(18, 18, 18)
                        .addComponent(rbt2)
                        .addGap(18, 18, 18)
                        .addComponent(rbt3))
                    .addComponent(lblPopis)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbt7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtNic)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbt8)
                                .addGap(18, 18, 18)
                                .addComponent(rbt9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPopis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt1)
                    .addComponent(rbt2)
                    .addComponent(rbt3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt4)
                    .addComponent(rbt5)
                    .addComponent(rbt6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt7)
                    .addComponent(rbt8)
                    .addComponent(rbt9))
                .addGap(18, 18, 18)
                .addComponent(tbtNic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgVolba;
    private javax.swing.JLabel lblPopis;
    private javax.swing.JRadioButton rbt1;
    private javax.swing.JRadioButton rbt2;
    private javax.swing.JRadioButton rbt3;
    private javax.swing.JRadioButton rbt4;
    private javax.swing.JRadioButton rbt5;
    private javax.swing.JRadioButton rbt6;
    private javax.swing.JRadioButton rbt7;
    private javax.swing.JRadioButton rbt8;
    private javax.swing.JRadioButton rbt9;
    private javax.swing.JRadioButton tbtNic;
    // End of variables declaration//GEN-END:variables
}
